Wdp220201 20 "RWD – zapisywanie w stanie aplikacji aktualnego trybu RWD"
odevpl/wdp-2202-01 pull request #23
Opened 2022-02-14 17:54 UTC by martanara

_MainLayout w momencie podłączenia musi uruchamiać listenera na zmiany szerokości viewportu, żeby na tej podstawie ustawiać w stanie aplikacji aktualny tryb (desktop, tablet albo mobile).
Trzeba to wykorzystać na początek w sekcji "New furniture" – tam obecnie wyświetla się zawsze 8 produktów per strona, a ma być różna ilość w zależności od trybu RWD:
8 na desktopie
na tablecie i mobilce tyle, ile się mieści w jednym wierszu (jest osobne zadania na RWD tego komponentu, od tamtego zadania zależy czy ile będzie w rzędzie)._

**Komentarz:** To było dla mnie dość trudne zadanie, nie mam pewności czy to jest najlepszy sposób żeby to rozwiązać. Nie mogłam znaleźć sposobu który by sprawiał. Rozwiązanie działa w trybie responsywnym czyli w przypadku po prostu zmiany manualnej wielkości ekranu na desktopie, nadal jest to desktop więc liczba produktów będzie taka sama.

2022-02-16 15:13 UTC, alfesen requested changes
Hey, kod prezentuje się ładnie, ale może dałabyś radę jakoś wyskalować kafelki w NewFurniture i je wypośrodkować, bo na szerokości 767 są wąskie i przyciski lekko się najeżdżają, a na mniejszych szerokościach jeszcze są umieszczone po lewej, tak że prawa część jest pustawa.

+ rozwiązanie konfliktów, Całość objektu categoryProducts ma być w pętli pod tablicą pages, żeby Swipeable się nie rozjechał

2022-02-16 16:02 UTC, martanara commented
Hej, dzięki za uwagi! Zaraz rozwiążę konflikty

2022-02-16 16:54 UTC, martanara commented
Niestety coś mi się kompletnie posypało z babel-eslint i nie wiem jak to ogarnąć, nie mówiąc o tym, że chyba to rozwiązanie przestało działać po usunięciu konfliktów. Będę to musiała przesunąć na jutro. Dam znać kiedy rozwiążę problemy.

2022-02-16 18:10 UTC, alfesen commented
> Niestety coś mi się kompletnie posypało z babel-eslint i nie wiem jak to ogarnąć, nie mówiąc o tym, że chyba to rozwiązanie przestało działać po usunięciu konfliktów. Będę to musiała przesunąć na jutro. Dam znać kiedy rozwiążę problemy.

Powinno wystarczyć usunięcie linijek 115-138 czyli między <div class='row'> a Swipeable

2022-02-16 20:00 UTC, martanara commented
Tak właśnie zrobiłam, ale teraz to rozwiązanie działa tylko jak się odświeży stronę. Nie updatuje się automatycznie. Muszę na to spojrzeć jutro...

2022-02-22 16:28 UTC, alfesen approved these changes
:)

2022-02-23 08:40 UTC, merged